## Read in cp3

In [1]:
import pandas as pd
import re
import os

In [2]:
INPUT_CSV = (
   "/Users/sreej/Desktop/Gateway_lawrence/gatewayinitiative-lawrencepd/0_RecompiledScripts/checkpoint3_geocoded_2526.csv"
)

OUTPUT_CSV = (
    "/Users/sreej/Desktop/Gateway_lawrence/gatewayinitiative-lawrencepd/0_RecompiledScripts/checkpoint4_cleaned_addresses.csv"
)
df = pd.read_csv(INPUT_CSV, low_memory=False)

print(f"Loaded: {INPUT_CSV}")
print(f"Rows: {len(df):,}")
print(f"Columns: {len(df.columns):,}")

display(df.head())
with pd.option_context('display.max_rows', None):
    print(df['Location'].value_counts())

Loaded: /Users/sreej/Desktop/Gateway_lawrence/gatewayinitiative-lawrencepd/0_RecompiledScripts/checkpoint3_geocoded_2526.csv
Rows: 66,741
Columns: 16

,Incident #,Date,Type,Location,Arrested,Location Prefix,Name,DOB,Charges,raw_address,cleaned_address,latitude,longitude,geocode_confidence,geocoded_at,coord_valid
0,25026764.0,2025-07-01 00:12:08,THREATS,259 ANDOVER ST,No,NaN,NaN,NaN,NaN,259 ANDOVER ST,"259 ANDOVER ST, Lawrence, MA",42.694842,-71.155948,10.0,2026-06-22T23:33:38.335777+00:00,True
1,25026765.0,2025-07-01 00:19:36,TOW/REPOSSED,454 HAMPSHIRE ST,No,NaN,NaN,NaN,NaN,454 HAMPSHIRE ST,"454 HAMPSHIRE ST, Lawrence, MA",42.717278,-71.171768,10.0,2026-06-25T23:39:24.046150+00:00,True
2,25026766.0,2025-07-01 00:49:07,DISTURBANCE,155 HAVERHILL ST,No,NaN,NaN,NaN,NaN,155 HAVERHILL ST,"155 HAVERHILL ST, Lawrence, MA",42.710380,-71.161736,10.0,2026-06-19T16:04:18.901970+00:00,True
3,25026767.0,2025-07-01 01:15:01,CK WELL BEING,621 COMMON ST,No,NaN,NaN,NaN,NaN,621 COMMON ST,"621 COMMON ST, Lawrence, MA",42.705034,-71.169622,10.0,2026-06-26T19:04:44.576031+00:00,True
4,25026769.0,2025-07-01 01:29:06,EXTRA SURVEIL,425 MERRIMACK ST,No,NaN,NaN,NaN,NaN,425 MERRIMACK ST,"425 MERRIMACK ST, Lawrence, MA",42.703240,-71.143607,10.0,2026-06-25T22:01:03.147567+00:00,True

Location
90 LOWELL ST                                 1038
50 BROADWAY                                   848
700 ESSEX ST                                  353
266 BROADWAY                                  336
296 ESSEX ST                                  327
73 WINTHROP AV                                309
370 BROADWAY                                  306
211 MERRIMACK ST                              273
BAY STATE RD                                  268
101 AMESBURY ST                               259
205 BROADWAY                                  257
164 MT VERNON ST                              247
BROADWAY & LOWELL ST                          242
550 BROADWAY                                  236
BROADWAY & ESSEX ST                           233
75 MANCHESTER ST                              222
240 CANAL ST                                  218
MARION AV                                     212
555 BROADWAY                                  208
MERRIMACK ST & S UNION ST                     207
70 N PARISH RD                                197
320 S BROADWAY                                196
187 BROADWAY                                  194
300 HAMPSHIRE ST                              191
1 GENERAL ST                                  190
29 EVERETT ST                                 187
55 HAMPSHIRE ST                               184
280 MERRIMACK ST                              182
615 BROADWAY                                  177
BROOK ST                                      168
99 WINTHROP AV                                168
165 CRAWFORD ST                               167
86 HIGH ST                                    163
BROADWAY & COMMON ST                          158
BRADFORD ST & BROADWAY                        157
BROADWAY & HAVERHILL ST                       151
300 METHUEN ST                                150
BROADWAY & WATER ST                           149
250 MERRIMACK ST                              147
125 AMESBURY ST                               145
S UNION ST & WINTHROP AV                      142
370 N CANAL ST                                137
S BROADWAY & SHATTUCK ST                      134
DAISY ST & HOLLY ST                           134
MERRIMACK ST & PARKER ST                      133
HAVERHILL ST & LAWRENCE ST                    132
67 WINTHROP AV                                132
425 MERRIMACK ST                              132
CANAL ST & UNION ST                           132
590 BROADWAY                                  131
200 COMMON ST                                 128
99 AMESBURY ST                                127
305 S BROADWAY                                127
1 MILL ST                                     126
486 ESSEX ST                                  125
ESSEX ST & LAWRENCE ST                        122
AMESBURY ST & ESSEX ST                        121
MERRIMACK ST & S BROADWAY                     119
255 E HAVERHILL ST                            118
215 S BROADWAY                                118
ESSEX ST & JACKSON ST                         116
183 HAVERHILL ST                              116
608 BROADWAY                                  113
220 MERRIMACK ST                              111
85 BAY STATE RD                               110
CAMBRIDGE ST & WINTHROP AV                    110
450 ESSEX ST                                  108
MARKET ST & S UNION ST                        106
80 BODWELL ST                                 103
HAVERHILL ST & JACKSON ST                     103
HOWARD ST                                     102
GRAFTON ST & WINTHROP AV                      101
EMBANKMENT RD                                 101
50 HIGH ST                                     99
233 HAVERHILL ST                               99
ANDOVER ST & S BROADWAY                        96
300 CANAL ST                                   96
380 BROADWAY                                   93
DORCHESTER ST & WINTHROP AV                    93
NIGHTINGALE CT                                 92
52 S UNION ST                                  91
317 HAMPSHIRE ST                               89
220 S BROADWAY                                 88
HIGH ST                                        88
85 MANCHESTER ST                               88
500 MERRIMACK ST                               87
HAMPSHIRE ST & LOWELL ST                       87
LAWRENCE ST & MYRTLE ST                        87
2 SARATOGA ST                                  85
COMMON ST & NEWBURY ST                         85
COMMON ST & JACKSON ST                         84
37 AUBURN ST                                   83
135 BROADWAY                                   83
92 BROADWAY                                    83
GREENFIELD ST                                  82
BROADWAY & CROSS ST                            82
APPLETON ST & ESSEX ST                         82
LAWRENCE ST & PARK ST                          82
AMESBURY ST & COMMON ST                        81
225 ESSEX ST                                   79
4 UNION ST                                     78
S UNION ST & SALEM ST                          77
AMESBURY ST & LOWELL ST                        76
COMMON ST & LAWRENCE ST                        76
ESSEX ST & HAMPSHIRE ST                        75
FRANKLIN ST & HAVERHILL ST                     75
100 ERVING AV                                  75
ESSEX ST & FRANKLIN ST                         74
105 BROADWAY                                   74
79 WINTHROP AV                                 72
BROADWAY & TREMONT ST                          72
180 CRAWFORD ST                                71
ERVING AV & SARATOGA ST                        69
71 N PARISH RD                                 69
BROADWAY & ISABEL MELENDEZ ST                  69
BROADWAY & MANCHESTER ST                       68
136 WATER ST                                   68
COMMON ST & HAMPSHIRE ST                       68
139 MARSTON ST                                 67
ESSEX ST & WINTER ST                           67
HAVERHILL ST & WEST ST                         66
ESSEX ST & UNION ST                            66
111 LOWELL ST                                  66
360 BROADWAY                                   65
15 UNION ST                                    65
AMESBURY ST & CANAL ST                         64
HAMPSHIRE ST & HAVERHILL ST                    64
703 HAVERHILL ST                               64
JUNIPER ST                                     64
BROADWAY & PARK ST                             63
439 S UNION ST                                 63
CARVER ST & MERRIMACK ST                       62
ANDOVER ST & WINTHROP AV                       61
415 BROADWAY                                   61
BOXFORD ST & WINTHROP AV                       60
ANDOVER ST & S UNION ST                        60
69 PARKER ST                                   60
FRANKLIN ST & LOWELL ST                        60
460 S UNION ST                                 59
19 WINTER ST                                   59
578 ESSEX ST                                   59
34 HAVERHILL ST                                59
AMESBURY ST & METHUEN ST                       59
AMESBURY ST & HAVERHILL ST                     58
31 AUBURN ST                                   58
599 CANAL ST                                   58
32 LAWRENCE ST                                 57
ESSEX ST & MARGIN ST                           57
EXETER ST                                      57
DURSO AV & WINTHROP AV                         57
47 ALDER ST                                    56
S BROADWAY & SALEM ST                          56
5 S UNION ST                                   55
LAWRENCE ST & MAPLE ST                         55
12 METHUEN ST                                  55
215 CANAL ST                                   55
CHICKERING ST & WINTHROP AV                    54
478 RIVERSIDE DR                               53
1 CENTRAL BRIDGE                               53
ERVING AV & LAWRENCE ST                        52
14 BROADWAY AV                                 52
CAMBRIDGE ST & S UNION ST                      52
BENNINGTON ST & ERVING AV                      51
530 BROADWAY                                   51
112 MARSTON ST                                 51
8 S BROADWAY                                   51
103 BROADWAY                                   51
94 BRADFORD ST                                 51
2 APPLETON ST                                  50
450 HAVERHILL ST                               50
LAWRENCE ST & LOWELL ST                        50
108 NEWBURY ST                                 50
LEBANON ST & WHITE ST                          50
360 MERRIMACK ST                               49
MARKET ST & PARKER ST                          49
248 BROADWAY                                   49
CROSBY ST & S BROADWAY                         48
LOWELL ST & OXFORD ST                          48
160 WINTHROP AV                                48
BELKNAP ST & EVERETT ST                        48
ESSEX ST & NEWBURY ST                          47
99 BRADFORD ST                                 47
141 WINTHROP AV                                47
HANCOCK ST                                     47
BROADWAY & METHUEN ST                          46
60 ESSEX ST                                    46
51 LAWRENCE ST                                 46
60 ALLEN ST                                    46
51 S CANAL ST                                  46
150 PARK ST                                    45
290 MERRIMACK ST                               45
ANDOVER ST & PARKER ST                         45
HAVERHILL ST & WHITE ST                        45
200 PARKER ST                                  45
METHUEN ST & UNION ST                          44
2 AMESBURY ST                                  44
31 BERESFORD ST                                43
WOODLAND ST                                    43
ACTON ST & BROADWAY                            43
224 WINTHROP AV                                43
ISLAND ST                                      43
BOXFORD ST & S UNION ST                        42
6 CHICKERING ST                                42
GRAFTON ST & S UNION ST                        42
151 ESSEX ST                                   42
77 S UNION ST                                  42
DORCHESTER ST & S UNION ST                     42
LAWRENCE ST & OAK ST                           41
ANDOVER ST & BLANCHARD ST                      41
WINTHROP AV                                    41
BERKELEY ST & JACKSON ST                       41
BAILEY ST & S UNION ST                         41
2 FALLS BRIDGE                                 40
THORNTON AV                                    40
COMMON ST & FRANKLIN ST                        40
112 RIVER POINTE WY                            40
26 CARVER ST                                   40
FALMOUTH ST & S UNION ST                       39
PARKER ST & SALEM ST                           39
RESERVOIR PARK                                 39
40 LAWRENCE ST                                 39
582 ESSEX ST                                   39
JACKSON ST & PARK ST                           39
434 BROADWAY                                   39
309 PARK ST                                    38
35 S BROADWAY                                  38
AVON ST & JACKSON ST                           38
BRADFORD ST & HAMPSHIRE ST                     38
E HAVERHILL ST & PROSPECT ST                   38
HAMPSHIRE ST & LEBANON ST                      38
20 KNOX ST                                     38
135 BUTLER ST                                  38
122 HANCOCK ST                                 38
619 ESSEX ST                                   37
S UNION ST                                     37
EXETER ST & WINTHROP AV                        37
240 CANAL ST #BUILDING                         37
195 LOWELL ST                                  37
99 HAMPSHIRE ST                                36
11 LAWRENCE ST                                 36
345 AMES ST                                    36
150 ARLINGTON ST                               36
50 ESSEX ST                                    36
CARVER ST & SALEM ST                           36
336 COMMON ST                                  36
50 ISLAND ST                                   36
270 CANAL ST                                   36
60 ISLAND ST                                   36
145 LAWRENCE ST                                36
621 ESSEX ST                                   35
APPLETON ST & METHUEN ST                       35
BROADWAY & GREEN ST                            35
25 MARSTON ST                                  35
198 ESSEX ST                                   35
106 COMMON ST                                  35
190 LAWRENCE ST                                35
72 GENERAL ST                                  35
412 HAMPSHIRE ST                               35
ESSEX ST & MILL ST                             34
222 WINTHROP AV                                34
1 FALLS BRIDGE                                 34
FRANKLIN ST & METHUEN ST                       34
BROADWAY & CANAL ST                            33
FALLS BRIDGE                                   33
HAMPSHIRE ST & PARK ST                         33
ARLINGTON ST & BROADWAY                        33
100 LOWELL ST                                  33
2 INMAN ST                                     33
21 DEBBIE LN                                   33
1 COMMONWEALTH DR                              32
MANCHESTER ST & MAY ST                         32
261 BROADWAY                                   32
33 S BROADWAY                                  32
CENTRAL BRIDGE                                 32
255 ESSEX ST                                   32
33 HAMLET ST                                   32
120 BROADWAY                                   32
210 PHILLIPS ST                                32
15 MEDFORD ST                                  32
391 CHESTNUT ST                                32
PHILLIPS ST & WINTHROP AV                      32
265 MERRIMACK ST                               31
226 WINTHROP AV                                31
570 S UNION ST                                 31
CANAL ST & MILL ST                             31
HAVERHILL ST & UNION ST                        31
371 MARKET ST                                  31
FERN ST & LAWRENCE ST                          31
WEST ST                                        31
354 MERRIMACK ST                               31
JACKSON ST & METHUEN ST                        31
AMES ST & YALE ST                              30
AMESBURY ST & LEBANON ST                       30
OSGOOD ST & SALEM ST                           30
2 CENTRAL BRIDGE                               30
MARKET ST & OSGOOD ST                          30
GARDEN ST & JACKSON ST                         30
109 LAWRENCE ST                                29
MT VERNON ST & S BROADWAY                      29
286 BROADWAY                                   29
63 MYRTLE ST                                   29
383 HAVERHILL ST                               29
BROADWAY & CEDAR ST                            29
MARSTON ST & STORROW ST                        29
611 COMMON ST                                  29
131 S UNION ST                                 29
LOWELL ST & MILTON ST                          29
623 ESSEX ST                                   29
282 BROADWAY                                   29
METHUEN ST & MILL ST                           29
43 JACKSON ST                                  28
HIGH ST & STORROW ST                           28
123 LAWRENCE ST                                28
90 WINTHROP AV                                 28
155 HAVERHILL ST                               28
ERVING AV & JACKSON ST                         28
MARLBORO ST & S UNION ST                       28
18 FRANKLIN ST                                 28
210 MERRIMACK ST                               28
203 HAVERHILL ST                               28
HAVERHILL ST & MORTON ST                       28
BROADWAY & VALLEY ST                           28
631 ESSEX ST                                   28
FRANKLIN ST & TREMONT ST                       28
80 WINTHROP AV                                 28
1 EXETER ST                                    28
165 S UNION ST                                 27
245 LAWRENCE ST                                27
267 MERRIMACK ST                               27
75 NEWTON ST                                   27
HOLLY ST                                       27
270 E HAVERHILL ST                             27
CANAL ST & FRANKLIN ST                         27
12 DAISY ST                                    27
160 S BROADWAY                                 27
DURHAM ST & S BROADWAY                         27
258 E HAVERHILL ST                             27
451 HOWARD ST                                  27
KENT ST & S UNION ST                           27
600 ESSEX ST                                   27
473 ESSEX ST                                   27
ESSEX ST & WARREN ST                           27
35 COMMON ST                                   26
GENERAL ST & UNION ST                          26
14 AMESBURY ST                                 26
ARLINGTON ST & LAWRENCE ST                     26
322 S BROADWAY                                 26
18 BELLEVUE ST                                 26
FITZ ST & LAWRENCE ST                          26
HAMPSHIRE ST & METHUEN ST                      26
N PARISH RD & OSGOOD ST                        26
170 CRAWFORD ST                                26
242 HAMPSHIRE ST                               26
LOWELL ST & WINTER ST                          26
1 CANAL ST                                     26
LOWELL ST & MARGIN ST                          26
333 ESSEX ST                                   26
JACKSON ST & OAK ST                            26
292 PROSPECT ST                                26
ELM ST & NEWBURY ST                            25
55 AUBURN ST                                   25
PARKER ST & SPRINGFIELD ST                     25
490 HAMPSHIRE ST                               25
242 MT VERNON ST                               25
E HAVERHILL ST & FERRY ST                      25
ELM ST & JACKSON ST                            25
305 ESSEX ST                                   25
70-71 N PARISH RD                              25
BRUCE ST & ERVING AV                           25
355 PARK ST                                    25
BRUCE ST & PARK ST                             25
FARNHAM ST & S UNION ST                        25
526 LOWELL ST                                  25
BAILEY ST                                      25
20 ISLAND ST                                   25
154 S BROADWAY                                 25
MARSTON ST & PROSPECT ST                       25
431 COMMON ST                                  24
2 MUSEUM SQ                                    24
341 S BROADWAY                                 24
599 ANDOVER ST                                 24
ANDOVER ST & BROOKFIELD ST                     24
73 WINTHROP AVE                                24
JAMAICA ST & S UNION ST                        24
HAVERHILL ST & MARGIN ST                       24
S UNION ST & SPRINGFIELD ST                    24
170 LAWRENCE ST                                24
2 ARROW TER                                    24
LAWRENCE ST                                    24
HAVERHILL ST & NEWBURY ST                      24
GLENN ST                                       24
17 WILLOUGHBY ST FL 1                          24
LYNN ST & S UNION ST                           24
COMMON ST & UNION ST                           24
91 COMMON ST                                   24
HAVERHILL ST & OXFORD ST                       23
AMES ST & LOWELL ST                            23
375 BROADWAY                                   23
BERKELEY ST & BRUCE ST                         23

## Clean up stuff we missed before the api calls

In [3]:
def clean_address_after_merge(address):
    """
    Clean the Location value after the geocoding merge.

    The function:
    - Converts text to uppercase
    - Removes periods, apostrophes, and backticks
    - Removes unwanted police-report prefixes/labels
    - Converts STREET to ST
    - Removes floor, apartment, and unit identifiers
    - Removes '#' and the characters attached to it until whitespace
    - Normalizes whitespace
    """
    if pd.isna(address):
        return ""

    address = str(address).upper().strip()

    # ---------------------------------------------------------
    # 1. Remove unwanted police-report terms
    # ---------------------------------------------------------
    unwanted_patterns = [
    r"\bREC\s*/\s*STOLEN\s+ARREST\b",
    r"\bARREST\s*/",
    r"\bV\s+TRUST\s*/",
    r"\bV\s+STOP\s*/",
    r"\bTOWED\b",
    r"\bWALK\s+IN\b",
    r"\bWALKIN\s*/",
    r"\bTOW\s*/",
    r"\bSTOP\s*/",
    r"\bV\s*/",
]

    for pattern in unwanted_patterns:
        address = re.sub(
            pattern,
            " ",
            address,
            flags=re.IGNORECASE,
        )
    
# Remove anything inside parentheses (including the parentheses)
# Examples:
# (REAR)
# (A)
# (PARKING LOT)
    address = re.sub(r"\([^)]*\)", " ", address)
    # Remove punctuation characters
# Examples:
# 150` ANDOVER ST
# 217 E HAVERHILL ST'
# 17 CYPRESS AVE.
# 23 BROADWAY°
    address = re.sub(r"[.'`°]", "", address)

    # ---------------------------------------------------------
    # 3. Standardize STREET to ST
    # ---------------------------------------------------------
    # 473 HAVERHILL STREET -> 473 HAVERHILL ST
    address = re.sub(
        r"\bSTREET\b",
        "ST",
        address,
        flags=re.IGNORECASE,
    )

    # ---------------------------------------------------------
    # 4. Remove floor identifiers
    # ---------------------------------------------------------
    # Handles:
    # 218 PARK ST FL 2
    # 300 CANAL ST FL3
    # 300 CANAL ST FLOOR 3
    #
    # Only removes the floor identifier, not everything after it.
    address = re.sub(
    r"\b(?:FLOOR\s*#?\s*[A-Z0-9-]+|FL\s*#?\s*\d+[A-Z0-9-]*)\b",
    " ",
    address,
    flags=re.IGNORECASE,
)

    # Remove FL or FLOOR when no value follows
   

    # ---------------------------------------------------------
    # 5. Remove apartment and unit identifiers
    # ---------------------------------------------------------
    # Handles:
    # APT 2
    # APT2
    # APARTMENT 4B
    # UNIT #5
    address = re.sub(
        r"\b(?:APT|APARTMENT|UNIT)\s*#?\s*[A-Z0-9-]+\b",
        " ",
        address,
        flags=re.IGNORECASE,
    )

    # Remove standalone APT, APARTMENT, or UNIT
    address = re.sub(
        r"\b(?:APT|APARTMENT|UNIT)\b",
        " ",
        address,
        flags=re.IGNORECASE,
    )

    # ---------------------------------------------------------
    # 6. Remove '#' and anything attached to it until whitespace
    # ---------------------------------------------------------
    # Examples:
    # 218 BROADWAY #1ST       -> 218 BROADWAY
    # 300 CANAL ST #311 FL3   -> 300 CANAL ST FL3
    #
    # FL3 is then removed by the floor rule above.
    address = re.sub(
        r"#\S*",
        " ",
        address,
    )

    # Remove any standalone number signs that remain
    address = address.replace("#", " ")

    # ---------------------------------------------------------
    # 7. Normalize whitespace
    # ---------------------------------------------------------
    address = re.sub(r"\s+", " ", address).strip()

    return address

## TEST

In [37]:
test_addresses = [
    "150` ANDOVER ST",
    "150` ARLINGTON ST",
    "17 CYPRESS AVE.",
    "217 E HAVERHILL ST'",
    "218 BROADWAY #1ST",
    "218 PARK ST FL 2",
    "300 CANAL ST #311 FL3",
    "473 HAVERHILL STREET",
    "V STOP / 250 BROADWAY",
    "STOP / 250 BROADWAY",
    "V / 250 BROADWAY",
    "V TRUST / 250 BROADWAY",
    "TOW/ 250 BROADWAY",
    "TOWED 250 BROADWAY",
    "WALK IN 250 BROADWAY",
    "REC/STOLEN ARREST 250 BROADWAY",
]

test_results = pd.DataFrame({
    "original": test_addresses,
    "cleaned": [
        clean_address_after_merge(address)
        for address in test_addresses
    ],
})

display(test_results)

                          original             cleaned
0                  150` ANDOVER ST      150 ANDOVER ST
1                150` ARLINGTON ST    150 ARLINGTON ST
2                  17 CYPRESS AVE.      17 CYPRESS AVE
3              217 E HAVERHILL ST'  217 E HAVERHILL ST
4                218 BROADWAY #1ST        218 BROADWAY
5                 218 PARK ST FL 2         218 PARK ST
6            300 CANAL ST #311 FL3        300 CANAL ST
7             473 HAVERHILL STREET    473 HAVERHILL ST
8            V STOP / 250 BROADWAY        250 BROADWAY
9              STOP / 250 BROADWAY        250 BROADWAY
10                V / 250 BROADWAY        250 BROADWAY
11          V TRUST / 250 BROADWAY        250 BROADWAY
12               TOW/ 250 BROADWAY        250 BROADWAY
13              TOWED 250 BROADWAY        250 BROADWAY
14            WALK IN 250 BROADWAY        250 BROADWAY
15  REC/STOLEN ARREST 250 BROADWAY        250 BROADWAY

In [4]:
cleaned_df = df.copy()

cleaned_df["cleaned_location"] = (
    cleaned_df["Location"]
    .apply(clean_address_after_merge)
)

print(f"Rows before cleaning: {len(df):,}")
print(f"Rows after cleaning: {len(cleaned_df):,}")

Rows before cleaning: 66,741
Rows after cleaning: 66,741

## Compare and consolidate addresses

In [5]:
comparison = cleaned_df[
    ["Location", "cleaned_location"]
].drop_duplicates()

changed = comparison[
    comparison["Location"].fillna("").astype(str).str.strip()
    != comparison["cleaned_location"]
]

print(f"Unique original locations: {cleaned_df['Location'].nunique(dropna=True):,}")
print(f"Unique cleaned locations: {cleaned_df['cleaned_location'].nunique(dropna=True):,}")
print(f"Unique values changed by cleaning: {len(changed):,}")

display(changed.head(50))

Unique original locations: 17,592
Unique cleaned locations: 13,407
Unique values changed by cleaning: 5,050

                            Location       cleaned_location
50                25 MARSTON ST #303          25 MARSTON ST
51                148 BUTLER ST FL 1          148 BUTLER ST
52   12 MAGINNIS AV #BUILDINGS- APT4         12 MAGINNIS AV
69                318 MARKET ST FL 3          318 MARKET ST
83                   74 UNION ST #31            74 UNION ST
89                56-58 KENT ST FL 1          56-58 KENT ST
90               40 LAWRENCE ST #313         40 LAWRENCE ST
112              300 METHUEN ST #427         300 METHUEN ST
117               134 FOSTER ST FL 1          134 FOSTER ST
124             266 BRROADWAY STREET       266 BRROADWAY ST
163            250 MERRIMACK ST #274       250 MERRIMACK ST
176            80 BENNINGTON ST FL 2       80 BENNINGTON ST
182                 115 EMMETT ST #3          115 EMMETT ST
215               77 S UNION ST #308          77 S UNION ST
229                35 COMMON ST #505           35 COMMON ST
244               32 LAWRENCE ST #39         32 LAWRENCE ST
246            12 KENDALL ST #2 FL 2          12 KENDALL ST
262               214 WALNUT ST FL 3          214 WALNUT ST
267               458 LOWELL ST FL 2          458 LOWELL ST
271                  248 SALEM ST #2           248 SALEM ST
299                  82 8S. BROADWAY         82 8S BROADWAY
335              103 HAVERHILL ST #1       103 HAVERHILL ST
352                    36 LAKE ST #B             36 LAKE ST
373           198 ESSEX ST #4 FL 401           198 ESSEX ST
374              24 FALMOUTH ST FL 3         24 FALMOUTH ST
378            36 WASHINGTON ST FL 1       36 WASHINGTON ST
380            383 HAVERHILL ST FL 2       383 HAVERHILL ST
405              2 SPRINGFIELD ST #9       2 SPRINGFIELD ST
427                258 ANDOVER ST #2         258 ANDOVER ST
449              258 ANDOVER ST FL 1         258 ANDOVER ST
458                685 ESSEX ST #213           685 ESSEX ST
464                582 ESSEX ST #213           582 ESSEX ST
469               24 BELMONT ST FL 1          24 BELMONT ST
474              300 METHUEN ST #406         300 METHUEN ST
489            84 BUNKERHILL ST FL 3       84 BUNKERHILL ST
503    681 ESSEX ST #APT 39 FL BLDG3  681 ESSEX ST FL BLDG3
511                   26 INMAN ST #4            26 INMAN ST
544                222 ESSEX ST #204           222 ESSEX ST
567              263 S UNION ST FL 2         263 S UNION ST
578                 225 BROADWAY #24           225 BROADWAY
604                440 S UNION ST #2         440 S UNION ST
639          579 HAVERHILL ST FL 1ST       579 HAVERHILL ST
672             298 LAWRENCE ST FL 1        298 LAWRENCE ST
686                 37 CAMDEN STREET           37 CAMDEN ST
709                  42 WHITE ST #69            42 WHITE ST
715                 113 GARDEN ST #2          113 GARDEN ST
728              5 THORNDIKE ST FL 2         5 THORNDIKE ST
748             653 ESSEX ST #7 FL 3           653 ESSEX ST
773                  46 MELVIN ST #9           46 MELVIN ST
801               35 WEBSTER CT FL 2          35 WEBSTER CT

In [6]:
collapsed = (
    cleaned_df.loc[
        cleaned_df["cleaned_location"].ne(""),
        ["cleaned_location", "Location"],
    ]
    .drop_duplicates()
    .groupby("cleaned_location")["Location"]
    .agg(list)
    .reset_index()
)

collapsed = collapsed[
    collapsed["Location"].apply(len) > 1
].copy()

collapsed["original_address_count"] = (
    collapsed["Location"].apply(len)
)

collapsed = collapsed.sort_values(
    "original_address_count",
    ascending=False,
)

print(f"Collapsed address groups: {len(collapsed):,}")

display(collapsed.head(50))

Collapsed address groups: 1,974

,cleaned_location,Location,original_address_count
5759,300 METHUEN ST,"[300 METHUEN ST #427, 300 METHUEN ST #406, 300...",95
4572,240 CANAL ST,"[240 CANAL ST, 240 CANAL ST #536 FL 5, 240 CAN...",55
4774,250 MERRIMACK ST,"[250 MERRIMACK ST, 250 MERRIMACK ST #274, 250 ...",50
6007,32 LAWRENCE ST,"[32 LAWRENCE ST #39, 32 LAWRENCE ST #48, 32 LA...",44
5744,300 CANAL ST,"[300 CANAL ST, 300 CANAL ST #221, 300 CANAL ST...",43
780,11 LAWRENCE ST,"[11 LAWRENCE ST, 11 LAWRENCE ST #2 FL 2, 11 LA...",41
10599,77 S UNION ST,"[77 S UNION ST, 77 S UNION ST #308, 77 S UNION...",37
4651,248 BROADWAY,"[248 BROADWAY, 248 BROADWAY #215, 248 BROADWAY...",36
3578,2 MUSEUM SQ,"[2 MUSEUM SQ, 2 MUSEUM SQ #216, 2 MUSEUM SQ #4...",35
9260,590 BROADWAY,"[590 BROADWAY, 590 BROADWAY #206, 590 BROADWAY...",33
10372,72 GENERAL ST,"[72 GENERAL ST #204, 72 GENERAL ST #223, 72 GE...",33
7200,4 UNION ST,"[4 UNION ST, 4 UNION ST #209, 4 UNION ST #209 ...",32
9486,608 BROADWAY,"[608 BROADWAY, 608 BROADWAY #G03, 608 BROADWAY...",32
6976,383 HAVERHILL ST,"[383 HAVERHILL ST FL 2, 383 HAVERHILL ST #29, ...",29
11110,86 S BROADWAY,"[86 S BROADWAY, 86 S BROADWAY #17, 86 S BROADW...",28
5107,270 CANAL ST,"[270 CANAL ST, 270 CANAL ST #518, 270 CANAL ST...",28
8956,550 BROADWAY,"[550 BROADWAY, 550 BROADWAY #412, 550 BROADWAY...",28
3990,210 MERRIMACK ST,"[210 MERRIMACK ST, 210 MERRIMACK ST #614, 210 ...",26
1937,141 AMESBURY ST,"[141 AMESBURY ST, 141 AMESBURY ST #602, 141 AM...",25
932,112 MARSTON ST,"[112 MARSTON ST, 112 MARSTON ST #116, 112 MARS...",19
168,1 S UNION ST,"[1 S UNION ST #204, 1 S UNION ST, 1 S UNION ST...",19
7794,45 BROADWAY,"[45 BROADWAY, 45 BROADWAY #A508, 45 BROADWAY #...",19
8256,490 HAMPSHIRE ST,"[490 HAMPSHIRE ST, 490 HAMPSHIRE ST #509 FL 5,...",18
3458,198 ESSEX ST,"[198 ESSEX ST #4 FL 401, 198 ESSEX ST #214, 19...",18
6460,35 COMMON ST,"[35 COMMON ST, 35 COMMON ST #505, 35 COMMON ST...",17
9252,59 TREMONT ST,"[59 TREMONT ST #108 FL 1, 59 TREMONT ST, 59 TR...",17
8069,473 ESSEX ST,"[473 ESSEX ST #34, 473 ESSEX ST, 473 ESSEX ST ...",16
8729,53 BRADFORD ST,"[53 BRADFORD ST #16B, 53 BRADFORD ST, 53 BRADF...",15
3016,18 FRANKLIN ST,"[18 FRANKLIN ST, 18 FRANKLIN ST #702B, 18 FRAN...",15
5920,312 WATER ST,"[312 WATER ST #6, 312 WATER ST, 312 WATER ST #...",15
6710,362 ESSEX ST,"[362 ESSEX ST #401, 362 ESSEX ST, 362 ESSEX ST...",14
7265,40 LAWRENCE ST,"[40 LAWRENCE ST #313, 40 LAWRENCE ST, 40 LAWRE...",14
9464,600 BROADWAY,"[600 BROADWAY #121, 600 BROADWAY, 600 BROADWAY...",14
4179,220 MERRIMACK ST,"[220 MERRIMACK ST, 220 MERRIMACK ST #630, 220 ...",14
6861,376 ESSEX ST,"[376 ESSEX ST, 376 ESSEX ST #407, 376 ESSEX ST...",13
4200,222 ESSEX ST,"[222 ESSEX ST #204, 222 ESSEX ST, 222 ESSEX ST...",13
6550,353 ELM ST,"[353 ELM ST, 353 ELM ST FL 4-5, 353 ELM ST #51...",12
3739,200 PARKER ST,"[200 PARKER ST, 200 PARKER ST #18, 200 PARKER ...",12
7084,393 CHESTNUT ST,"[393 CHESTNUT ST #135, 393 CHESTNUT ST #111, 3...",12
9827,65 UNION ST,"[65 UNION ST #406, 65 UNION STREET #210, 65 UN...",11
4233,225 ESSEX ST,"[225 ESSEX ST, 225 ESSEX ST #4, 225 ESSEX ST #...",11
2974,18 BEACON ST,"[18 BEACON ST #30, 18 BEACON ST, 18 BEACON ST ...",11
3394,193 MAPLE ST,"[193 MAPLE ST, 193 MAPLE ST #1M, 193 MAPLE ST ...",11
821,11 SUMMER ST,"[11 SUMMER ST #109, 11 SUMMER ST, 11 SUMMER ST...",10
8704,525 ESSEX ST,"[525 ESSEX ST, 525 ESSEX ST #26, 525 ESSEX ST ...",10
4817,257 BROADWAY,"[257 BROADWAY, 257 BROADWAY #3 FL 1, 257 BROAD...",10
11352,9 SUMMER ST,"[9 SUMMER ST, 9 SUMMER ST #709, 9 SUMMER ST #S...",10
6743,369 HAVERHILL ST,"[369 HAVERHILL ST, 369 HAVERHILL ST #302, 369 ...",10
2854,172 LAWRENCE ST,"[172 LAWRENCE ST #2B FL 2, 172 LAWRENCE ST #3A...",10
10867,800 ESSEX ST,"[800 ESSEX ST #101 FL 1, 800 ESSEX ST FL 1, 80...",10

In [9]:
with pd.option_context('display.max_rows', None):
    print(cleaned_df['Location'].value_counts())
coordinate_columns = [
    column
    for column in ["latitude", "longitude", "lat", "long"]
    if column in cleaned_df.columns
]

print("Coordinate columns found:", coordinate_columns)

if coordinate_columns:
    print(
        cleaned_df[coordinate_columns]
        .notna()
        .sum()
    )
display(cleaned_df.head())

Location
90 LOWELL ST                                 1038
50 BROADWAY                                   848
700 ESSEX ST                                  353
266 BROADWAY                                  336
296 ESSEX ST                                  327
73 WINTHROP AV                                309
370 BROADWAY                                  306
211 MERRIMACK ST                              273
BAY STATE RD                                  268
101 AMESBURY ST                               259
205 BROADWAY                                  257
164 MT VERNON ST                              247
BROADWAY & LOWELL ST                          242
550 BROADWAY                                  236
BROADWAY & ESSEX ST                           233
75 MANCHESTER ST                              222
240 CANAL ST                                  218
MARION AV                                     212
555 BROADWAY                                  208
MERRIMACK ST & S UNION ST                     207
70 N PARISH RD                                197
320 S BROADWAY                                196
187 BROADWAY                                  194
300 HAMPSHIRE ST                              191
1 GENERAL ST                                  190
29 EVERETT ST                                 187
55 HAMPSHIRE ST                               184
280 MERRIMACK ST                              182
615 BROADWAY                                  177
BROOK ST                                      168
99 WINTHROP AV                                168
165 CRAWFORD ST                               167
86 HIGH ST                                    163
BROADWAY & COMMON ST                          158
BRADFORD ST & BROADWAY                        157
BROADWAY & HAVERHILL ST                       151
300 METHUEN ST                                150
BROADWAY & WATER ST                           149
250 MERRIMACK ST                              147
125 AMESBURY ST                               145
S UNION ST & WINTHROP AV                      142
370 N CANAL ST                                137
S BROADWAY & SHATTUCK ST                      134
DAISY ST & HOLLY ST                           134
MERRIMACK ST & PARKER ST                      133
HAVERHILL ST & LAWRENCE ST                    132
67 WINTHROP AV                                132
425 MERRIMACK ST                              132
CANAL ST & UNION ST                           132
590 BROADWAY                                  131
200 COMMON ST                                 128
99 AMESBURY ST                                127
305 S BROADWAY                                127
1 MILL ST                                     126
486 ESSEX ST                                  125
ESSEX ST & LAWRENCE ST                        122
AMESBURY ST & ESSEX ST                        121
MERRIMACK ST & S BROADWAY                     119
255 E HAVERHILL ST                            118
215 S BROADWAY                                118
ESSEX ST & JACKSON ST                         116
183 HAVERHILL ST                              116
608 BROADWAY                                  113
220 MERRIMACK ST                              111
85 BAY STATE RD                               110
CAMBRIDGE ST & WINTHROP AV                    110
450 ESSEX ST                                  108
MARKET ST & S UNION ST                        106
80 BODWELL ST                                 103
HAVERHILL ST & JACKSON ST                     103
HOWARD ST                                     102
GRAFTON ST & WINTHROP AV                      101
EMBANKMENT RD                                 101
50 HIGH ST                                     99
233 HAVERHILL ST                               99
ANDOVER ST & S BROADWAY                        96
300 CANAL ST                                   96
380 BROADWAY                                   93
DORCHESTER ST & WINTHROP AV                    93
NIGHTINGALE CT                                 92
52 S UNION ST                                  91
317 HAMPSHIRE ST                               89
220 S BROADWAY                                 88
HIGH ST                                        88
85 MANCHESTER ST                               88
500 MERRIMACK ST                               87
HAMPSHIRE ST & LOWELL ST                       87
LAWRENCE ST & MYRTLE ST                        87
2 SARATOGA ST                                  85
COMMON ST & NEWBURY ST                         85
COMMON ST & JACKSON ST                         84
37 AUBURN ST                                   83
135 BROADWAY                                   83
92 BROADWAY                                    83
GREENFIELD ST                                  82
BROADWAY & CROSS ST                            82
APPLETON ST & ESSEX ST                         82
LAWRENCE ST & PARK ST                          82
AMESBURY ST & COMMON ST                        81
225 ESSEX ST                                   79
4 UNION ST                                     78
S UNION ST & SALEM ST                          77
AMESBURY ST & LOWELL ST                        76
COMMON ST & LAWRENCE ST                        76
ESSEX ST & HAMPSHIRE ST                        75
FRANKLIN ST & HAVERHILL ST                     75
100 ERVING AV                                  75
ESSEX ST & FRANKLIN ST                         74
105 BROADWAY                                   74
79 WINTHROP AV                                 72
BROADWAY & TREMONT ST                          72
180 CRAWFORD ST                                71
ERVING AV & SARATOGA ST                        69
71 N PARISH RD                                 69
BROADWAY & ISABEL MELENDEZ ST                  69
BROADWAY & MANCHESTER ST                       68
136 WATER ST                                   68
COMMON ST & HAMPSHIRE ST                       68
139 MARSTON ST                                 67
ESSEX ST & WINTER ST                           67
HAVERHILL ST & WEST ST                         66
ESSEX ST & UNION ST                            66
111 LOWELL ST                                  66
360 BROADWAY                                   65
15 UNION ST                                    65
AMESBURY ST & CANAL ST                         64
HAMPSHIRE ST & HAVERHILL ST                    64
703 HAVERHILL ST                               64
JUNIPER ST                                     64
BROADWAY & PARK ST                             63
439 S UNION ST                                 63
CARVER ST & MERRIMACK ST                       62
ANDOVER ST & WINTHROP AV                       61
415 BROADWAY                                   61
BOXFORD ST & WINTHROP AV                       60
ANDOVER ST & S UNION ST                        60
69 PARKER ST                                   60
FRANKLIN ST & LOWELL ST                        60
460 S UNION ST                                 59
19 WINTER ST                                   59
578 ESSEX ST                                   59
34 HAVERHILL ST                                59
AMESBURY ST & METHUEN ST                       59
AMESBURY ST & HAVERHILL ST                     58
31 AUBURN ST                                   58
599 CANAL ST                                   58
32 LAWRENCE ST                                 57
ESSEX ST & MARGIN ST                           57
EXETER ST                                      57
DURSO AV & WINTHROP AV                         57
47 ALDER ST                                    56
S BROADWAY & SALEM ST                          56
5 S UNION ST                                   55
LAWRENCE ST & MAPLE ST                         55
12 METHUEN ST                                  55
215 CANAL ST                                   55
CHICKERING ST & WINTHROP AV                    54
478 RIVERSIDE DR                               53
1 CENTRAL BRIDGE                               53
ERVING AV & LAWRENCE ST                        52
14 BROADWAY AV                                 52
CAMBRIDGE ST & S UNION ST                      52
BENNINGTON ST & ERVING AV                      51
530 BROADWAY                                   51
112 MARSTON ST                                 51
8 S BROADWAY                                   51
103 BROADWAY                                   51
94 BRADFORD ST                                 51
2 APPLETON ST                                  50
450 HAVERHILL ST                               50
LAWRENCE ST & LOWELL ST                        50
108 NEWBURY ST                                 50
LEBANON ST & WHITE ST                          50
360 MERRIMACK ST                               49
MARKET ST & PARKER ST                          49
248 BROADWAY                                   49
CROSBY ST & S BROADWAY                         48
LOWELL ST & OXFORD ST                          48
160 WINTHROP AV                                48
BELKNAP ST & EVERETT ST                        48
ESSEX ST & NEWBURY ST                          47
99 BRADFORD ST                                 47
141 WINTHROP AV                                47
HANCOCK ST                                     47
BROADWAY & METHUEN ST                          46
60 ESSEX ST                                    46
51 LAWRENCE ST                                 46
60 ALLEN ST                                    46
51 S CANAL ST                                  46
150 PARK ST                                    45
290 MERRIMACK ST                               45
ANDOVER ST & PARKER ST                         45
HAVERHILL ST & WHITE ST                        45
200 PARKER ST                                  45
METHUEN ST & UNION ST                          44
2 AMESBURY ST                                  44
31 BERESFORD ST                                43
WOODLAND ST                                    43
ACTON ST & BROADWAY                            43
224 WINTHROP AV                                43
ISLAND ST                                      43
BOXFORD ST & S UNION ST                        42
6 CHICKERING ST                                42
GRAFTON ST & S UNION ST                        42
151 ESSEX ST                                   42
77 S UNION ST                                  42
DORCHESTER ST & S UNION ST                     42
LAWRENCE ST & OAK ST                           41
ANDOVER ST & BLANCHARD ST                      41
WINTHROP AV                                    41
BERKELEY ST & JACKSON ST                       41
BAILEY ST & S UNION ST                         41
2 FALLS BRIDGE                                 40
THORNTON AV                                    40
COMMON ST & FRANKLIN ST                        40
112 RIVER POINTE WY                            40
26 CARVER ST                                   40
FALMOUTH ST & S UNION ST                       39
PARKER ST & SALEM ST                           39
RESERVOIR PARK                                 39
40 LAWRENCE ST                                 39
582 ESSEX ST                                   39
JACKSON ST & PARK ST                           39
434 BROADWAY                                   39
309 PARK ST                                    38
35 S BROADWAY                                  38
AVON ST & JACKSON ST                           38
BRADFORD ST & HAMPSHIRE ST                     38
E HAVERHILL ST & PROSPECT ST                   38
HAMPSHIRE ST & LEBANON ST                      38
20 KNOX ST                                     38
135 BUTLER ST                                  38
122 HANCOCK ST                                 38
619 ESSEX ST                                   37
S UNION ST                                     37
EXETER ST & WINTHROP AV                        37
240 CANAL ST #BUILDING                         37
195 LOWELL ST                                  37
99 HAMPSHIRE ST                                36
11 LAWRENCE ST                                 36
345 AMES ST                                    36
150 ARLINGTON ST                               36
50 ESSEX ST                                    36
CARVER ST & SALEM ST                           36
336 COMMON ST                                  36
50 ISLAND ST                                   36
270 CANAL ST                                   36
60 ISLAND ST                                   36
145 LAWRENCE ST                                36
621 ESSEX ST                                   35
APPLETON ST & METHUEN ST                       35
BROADWAY & GREEN ST                            35
25 MARSTON ST                                  35
198 ESSEX ST                                   35
106 COMMON ST                                  35
190 LAWRENCE ST                                35
72 GENERAL ST                                  35
412 HAMPSHIRE ST                               35
ESSEX ST & MILL ST                             34
222 WINTHROP AV                                34
1 FALLS BRIDGE                                 34
FRANKLIN ST & METHUEN ST                       34
BROADWAY & CANAL ST                            33
FALLS BRIDGE                                   33
HAMPSHIRE ST & PARK ST                         33
ARLINGTON ST & BROADWAY                        33
100 LOWELL ST                                  33
2 INMAN ST                                     33
21 DEBBIE LN                                   33
1 COMMONWEALTH DR                              32
MANCHESTER ST & MAY ST                         32
261 BROADWAY                                   32
33 S BROADWAY                                  32
CENTRAL BRIDGE                                 32
255 ESSEX ST                                   32
33 HAMLET ST                                   32
120 BROADWAY                                   32
210 PHILLIPS ST                                32
15 MEDFORD ST                                  32
391 CHESTNUT ST                                32
PHILLIPS ST & WINTHROP AV                      32
265 MERRIMACK ST                               31
226 WINTHROP AV                                31
570 S UNION ST                                 31
CANAL ST & MILL ST                             31
HAVERHILL ST & UNION ST                        31
371 MARKET ST                                  31
FERN ST & LAWRENCE ST                          31
WEST ST                                        31
354 MERRIMACK ST                               31
JACKSON ST & METHUEN ST                        31
AMES ST & YALE ST                              30
AMESBURY ST & LEBANON ST                       30
OSGOOD ST & SALEM ST                           30
2 CENTRAL BRIDGE                               30
MARKET ST & OSGOOD ST                          30
GARDEN ST & JACKSON ST                         30
109 LAWRENCE ST                                29
MT VERNON ST & S BROADWAY                      29
286 BROADWAY                                   29
63 MYRTLE ST                                   29
383 HAVERHILL ST                               29
BROADWAY & CEDAR ST                            29
MARSTON ST & STORROW ST                        29
611 COMMON ST                                  29
131 S UNION ST                                 29
LOWELL ST & MILTON ST                          29
623 ESSEX ST                                   29
282 BROADWAY                                   29
METHUEN ST & MILL ST                           29
43 JACKSON ST                                  28
HIGH ST & STORROW ST                           28
123 LAWRENCE ST                                28
90 WINTHROP AV                                 28
155 HAVERHILL ST                               28
ERVING AV & JACKSON ST                         28
MARLBORO ST & S UNION ST                       28
18 FRANKLIN ST                                 28
210 MERRIMACK ST                               28
203 HAVERHILL ST                               28
HAVERHILL ST & MORTON ST                       28
BROADWAY & VALLEY ST                           28
631 ESSEX ST                                   28
FRANKLIN ST & TREMONT ST                       28
80 WINTHROP AV                                 28
1 EXETER ST                                    28
165 S UNION ST                                 27
245 LAWRENCE ST                                27
267 MERRIMACK ST                               27
75 NEWTON ST                                   27
HOLLY ST                                       27
270 E HAVERHILL ST                             27
CANAL ST & FRANKLIN ST                         27
12 DAISY ST                                    27
160 S BROADWAY                                 27
DURHAM ST & S BROADWAY                         27
258 E HAVERHILL ST                             27
451 HOWARD ST                                  27
KENT ST & S UNION ST                           27
600 ESSEX ST                                   27
473 ESSEX ST                                   27
ESSEX ST & WARREN ST                           27
35 COMMON ST                                   26
GENERAL ST & UNION ST                          26
14 AMESBURY ST                                 26
ARLINGTON ST & LAWRENCE ST                     26
322 S BROADWAY                                 26
18 BELLEVUE ST                                 26
FITZ ST & LAWRENCE ST                          26
HAMPSHIRE ST & METHUEN ST                      26
N PARISH RD & OSGOOD ST                        26
170 CRAWFORD ST                                26
242 HAMPSHIRE ST                               26
LOWELL ST & WINTER ST                          26
1 CANAL ST                                     26
LOWELL ST & MARGIN ST                          26
333 ESSEX ST                                   26
JACKSON ST & OAK ST                            26
292 PROSPECT ST                                26
ELM ST & NEWBURY ST                            25
55 AUBURN ST                                   25
PARKER ST & SPRINGFIELD ST                     25
490 HAMPSHIRE ST                               25
242 MT VERNON ST                               25
E HAVERHILL ST & FERRY ST                      25
ELM ST & JACKSON ST                            25
305 ESSEX ST                                   25
70-71 N PARISH RD                              25
BRUCE ST & ERVING AV                           25
355 PARK ST                                    25
BRUCE ST & PARK ST                             25
FARNHAM ST & S UNION ST                        25
526 LOWELL ST                                  25
BAILEY ST                                      25
20 ISLAND ST                                   25
154 S BROADWAY                                 25
MARSTON ST & PROSPECT ST                       25
431 COMMON ST                                  24
2 MUSEUM SQ                                    24
341 S BROADWAY                                 24
599 ANDOVER ST                                 24
ANDOVER ST & BROOKFIELD ST                     24
73 WINTHROP AVE                                24
JAMAICA ST & S UNION ST                        24
HAVERHILL ST & MARGIN ST                       24
S UNION ST & SPRINGFIELD ST                    24
170 LAWRENCE ST                                24
2 ARROW TER                                    24
LAWRENCE ST                                    24
HAVERHILL ST & NEWBURY ST                      24
GLENN ST                                       24
17 WILLOUGHBY ST FL 1                          24
LYNN ST & S UNION ST                           24
COMMON ST & UNION ST                           24
91 COMMON ST                                   24
HAVERHILL ST & OXFORD ST                       23
AMES ST & LOWELL ST                            23
375 BROADWAY                                   23
BERKELEY ST & BRUCE ST                         23

,Incident #,Date,Type,Location,Arrested,Location Prefix,Name,DOB,Charges,raw_address,cleaned_address,latitude,longitude,geocode_confidence,geocoded_at,coord_valid,cleaned_location
0,25026764.0,2025-07-01 00:12:08,THREATS,259 ANDOVER ST,No,NaN,NaN,NaN,NaN,259 ANDOVER ST,"259 ANDOVER ST, Lawrence, MA",42.694842,-71.155948,10.0,2026-06-22T23:33:38.335777+00:00,True,259 ANDOVER ST
1,25026765.0,2025-07-01 00:19:36,TOW/REPOSSED,454 HAMPSHIRE ST,No,NaN,NaN,NaN,NaN,454 HAMPSHIRE ST,"454 HAMPSHIRE ST, Lawrence, MA",42.717278,-71.171768,10.0,2026-06-25T23:39:24.046150+00:00,True,454 HAMPSHIRE ST
2,25026766.0,2025-07-01 00:49:07,DISTURBANCE,155 HAVERHILL ST,No,NaN,NaN,NaN,NaN,155 HAVERHILL ST,"155 HAVERHILL ST, Lawrence, MA",42.710380,-71.161736,10.0,2026-06-19T16:04:18.901970+00:00,True,155 HAVERHILL ST
3,25026767.0,2025-07-01 01:15:01,CK WELL BEING,621 COMMON ST,No,NaN,NaN,NaN,NaN,621 COMMON ST,"621 COMMON ST, Lawrence, MA",42.705034,-71.169622,10.0,2026-06-26T19:04:44.576031+00:00,True,621 COMMON ST
4,25026769.0,2025-07-01 01:29:06,EXTRA SURVEIL,425 MERRIMACK ST,No,NaN,NaN,NaN,NaN,425 MERRIMACK ST,"425 MERRIMACK ST, Lawrence, MA",42.703240,-71.143607,10.0,2026-06-25T22:01:03.147567+00:00,True,425 MERRIMACK ST

In [10]:
cleaned_df = cleaned_df.drop(columns=["Source PDF"], errors="ignore")

In [11]:
# Replace Location with the cleaned version
cleaned_df["Location"] = cleaned_df["cleaned_location"]

# Remove the temporary column
cleaned_df = cleaned_df.drop(columns=["cleaned_location"])

## Create cp4

In [12]:
os.makedirs(
    os.path.dirname(OUTPUT_CSV),
    exist_ok=True,
)

cleaned_df.to_csv(
    OUTPUT_CSV,
    index=False,
)

print(f"Saved: {OUTPUT_CSV}")
print(f"Saved rows: {len(cleaned_df):,}")

Saved: /Users/sreej/Desktop/Gateway_lawrence/gatewayinitiative-lawrencepd/0_RecompiledScripts/checkpoint4_cleaned_addresses.csv
Saved rows: 66,741

## Verify

In [13]:
verification_df = pd.read_csv(
    OUTPUT_CSV,
    low_memory=False,
)

print(f"Reloaded rows: {len(verification_df):,}")
print(f"Reloaded columns: {len(verification_df.columns):,}")
print(
    "cleaned_location present:",
    "cleaned_location" in verification_df.columns,
)

display(
    verification_df[
        ["Location"]
    ].head(20)
)

Reloaded rows: 66,741
Reloaded columns: 16
cleaned_location present: False

                        Location
0                 259 ANDOVER ST
1               454 HAMPSHIRE ST
2               155 HAVERHILL ST
3                  621 COMMON ST
4               425 MERRIMACK ST
5                  EMBANKMENT RD
6                   BAY STATE RD
7                  GREENFIELD ST
8                     CONDUIT ST
9         MARKET ST & S UNION ST
10                       HIGH ST
11  NIGHTINGALE CT & CAULKINS CT
12                     HOWARD ST
13                     EXETER ST
14                  700 ESSEX ST
15                   WOODLAND ST
16          BROADWAY & COMMON ST
17                439 S UNION ST
18              164 MT VERNON ST
19                 29 EVERETT ST