# Add `is_misdemeanor` and `has_warrant` Columns

Adds two derived columns to checkpoint14 and saves checkpoint15.

- **`is_misdemeanor`**: `True` if every charge in the row classifies as `Misdemeanor` under MA law; `False` if any charge is `Felony`, `Either`, or `Unknown`; `NaN` for rows with no charges.
- **`has_warrant`**: `True` if any individual charge in the original `Charges` field carried a warrant prefix (bench warrant, default warrant, standard warrant, capias, child in need); `False` otherwise; `NaN` for rows with no charges.

**Input:** `data/checkpoints/checkpoint14_standardized_charges.csv`  
**Output:** `data/checkpoints/checkpoint15_misdemeanor_warrant.csv`

### Imports & Paths

In [9]:
import os
import numpy as np
import pandas as pd

from standardize_charges import extract_warrant_type

NOTEBOOK_DIR = os.getcwd()

DATA_DIR = os.path.join(
    NOTEBOOK_DIR,
    "..",
    "data",
    "missing_dates_csv",
)

CHECKPOINTS_DIR = os.path.join(DATA_DIR, "md_checkpoints")

IN_PATH = os.path.join(
    CHECKPOINTS_DIR,
    "checkpoint14_standardized_charges.csv",
)

OUT_PATH = os.path.join(
    CHECKPOINTS_DIR,
    "checkpoint15_misdemeanor_warrant.csv",
)


REPO_ROOT = os.path.abspath(
    os.path.join(NOTEBOOK_DIR, "..", "..")
)

LOOKUP_PATH = os.path.join(
    REPO_ROOT,
    "streamlit-app",
    "unique_charges_standardized.csv",
)

### Load checkpoint14

In [6]:
df = pd.read_csv(IN_PATH, low_memory=False)
display(df.head())
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")
print(f"Rows with charges: {df['cleaned_charges'].notna().sum()}")
df.head()

,Date,Type,Location,Arrested,Location Prefix,DOB,Charges,raw_address,latitude,longitude,...,person_id,category,Year,crime_severity,_DOB_raw,_Date_raw,DOB_dt,Date_dt,statutes,cleaned_charges
0,2018-01-01 00:01:14,NOISE ORD,3 HARRIMAN ST,Yes,NaN,07/03/1974,A&B ON FAMILY / HOUSEHOLD MEMBER / INTIMATE PA...,3 HARRIMAN ST,42.718522,-71.148148,...,20f72481f083d4756c89b98fd499514c5953a8a4c10253...,Public Disturbances,2018,Non-Serious,07/03/1974,2018-01-01 00:01:14,1974-07-03,2018-01-01 00:01:14,NaN,a&b on family / household member / intimate pa...
1,2018-01-01 00:08:38,LOUD NOISE,1 HARRIMAN ST,Yes,NaN,01/21/1979,A&B ON FAMILY / HOUSEHOLD MEMBER / INTIMATE PA...,1 HARRIMAN ST FL 2,42.718522,-71.148148,...,2d5adb553cad8a22fd72d2e390525997c4963bac1b185e...,Public Disturbances,2018,Non-Serious,01/21/1979,2018-01-01 00:08:38,1979-01-21,2018-01-01 00:08:38,NaN,a&b on family / household member / intimate pa...
2,2018-01-01 00:11:17,ALARM/BURG,16 ALLEN ST,No,MATOS,NaN,NaN,16 ALLEN ST,42.710782,-71.151911,...,NaN,Fire and Arson Incidents,2018,Non-Serious,NaN,2018-01-01 00:11:17,NaN,2018-01-01 00:11:17,NaN,NaN
3,2018-01-01 00:14:53,DISORDERLY,11 SUMMER ST,No,NaN,NaN,NaN,11 SUMMER ST,42.711117,-71.153015,...,NaN,Public Disturbances,2018,Non-Serious,NaN,2018-01-01 00:14:53,NaN,2018-01-01 00:14:53,NaN,NaN
4,2018-01-01 00:27:36,EXTRA SURVEIL,57 SPRINGFIELD ST,Yes,WARD SIX CLUB,06/26/2002,A&B DOMESTIC NO 209A IN EFFECT,57 SPRINGFIELD ST,42.699340,-71.156938,...,41c43f9f4255dee8e2c910e87f2a983e1b13beecf27eac...,Preventive Policing,2018,Non-Serious,06/26/2002,2018-01-01 00:27:36,2002-06-26,2018-01-01 00:27:36,NaN,a&b domestic no 209a in effect

Shape: (428527, 21)
Columns: ['Date', 'Type', 'Location', 'Arrested', 'Location Prefix', 'DOB', 'Charges', 'raw_address', 'latitude', 'longitude', 'geocode_confidence', 'person_id', 'category', 'Year', 'crime_severity', '_DOB_raw', '_Date_raw', 'DOB_dt', 'Date_dt', 'statutes', 'cleaned_charges']
Rows with charges: 4631

,Date,Type,Location,Arrested,Location Prefix,DOB,Charges,raw_address,latitude,longitude,...,person_id,category,Year,crime_severity,_DOB_raw,_Date_raw,DOB_dt,Date_dt,statutes,cleaned_charges
0,2018-01-01 00:01:14,NOISE ORD,3 HARRIMAN ST,Yes,NaN,07/03/1974,A&B ON FAMILY / HOUSEHOLD MEMBER / INTIMATE PA...,3 HARRIMAN ST,42.718522,-71.148148,...,20f72481f083d4756c89b98fd499514c5953a8a4c10253...,Public Disturbances,2018,Non-Serious,07/03/1974,2018-01-01 00:01:14,1974-07-03,2018-01-01 00:01:14,NaN,a&b on family / household member / intimate pa...
1,2018-01-01 00:08:38,LOUD NOISE,1 HARRIMAN ST,Yes,NaN,01/21/1979,A&B ON FAMILY / HOUSEHOLD MEMBER / INTIMATE PA...,1 HARRIMAN ST FL 2,42.718522,-71.148148,...,2d5adb553cad8a22fd72d2e390525997c4963bac1b185e...,Public Disturbances,2018,Non-Serious,01/21/1979,2018-01-01 00:08:38,1979-01-21,2018-01-01 00:08:38,NaN,a&b on family / household member / intimate pa...
2,2018-01-01 00:11:17,ALARM/BURG,16 ALLEN ST,No,MATOS,NaN,NaN,16 ALLEN ST,42.710782,-71.151911,...,NaN,Fire and Arson Incidents,2018,Non-Serious,NaN,2018-01-01 00:11:17,NaN,2018-01-01 00:11:17,NaN,NaN
3,2018-01-01 00:14:53,DISORDERLY,11 SUMMER ST,No,NaN,NaN,NaN,11 SUMMER ST,42.711117,-71.153015,...,NaN,Public Disturbances,2018,Non-Serious,NaN,2018-01-01 00:14:53,NaN,2018-01-01 00:14:53,NaN,NaN
4,2018-01-01 00:27:36,EXTRA SURVEIL,57 SPRINGFIELD ST,Yes,WARD SIX CLUB,06/26/2002,A&B DOMESTIC NO 209A IN EFFECT,57 SPRINGFIELD ST,42.699340,-71.156938,...,41c43f9f4255dee8e2c910e87f2a983e1b13beecf27eac...,Preventive Policing,2018,Non-Serious,06/26/2002,2018-01-01 00:27:36,2002-06-26,2018-01-01 00:27:36,NaN,a&b domestic no 209a in effect

### Build charge_class lookup

Load `unique_charges_standardized.csv` and build a dict: `base_charge → charge_class`.

In [19]:
#gffi
lookup_df = pd.read_csv(LOOKUP_PATH)

charge_class_lookup = dict(
    zip(
        lookup_df["base_charge"],
        lookup_df["charge_class"]
    )
)

print(f"Lookup entries: {len(charge_class_lookup)}")
print(f"Classes present: {sorted(lookup_df['charge_class'].dropna().unique())}")

print()
for sample in [
    "trespass",
    "murder",
    "firearm, carry without license",
    "drug, possess class a",
]:
    print(f"{sample!r} -> {charge_class_lookup.get(sample, 'NOT FOUND')}")

Lookup entries: 394
Classes present: ['Either', 'Felony', 'Misdemeanor']

'trespass' -> Misdemeanor
'murder' -> Felony
'firearm, carry without license' -> Either
'drug, possess class a' -> Misdemeanor

In [20]:
 
lookup_df = pd.read_csv(LOOKUP_PATH)
charge_class_lookup = dict(zip(lookup_df["base_charge"], lookup_df["charge_class"]))

print(f"Lookup entries: {len(charge_class_lookup)}")
print(f"Classes present: {set(charge_class_lookup.values())}")

# Quick sanity checks
print()
for sample in ["trespass", "murder", "firearm, carry without license", "drug, possess class a"]:
    print(f"  {sample!r} -> {charge_class_lookup.get(sample, 'NOT FOUND')}")

Lookup entries: 394
Classes present: {'Misdemeanor', 'Either', 'Felony'}

  'trespass' -> Misdemeanor
  'murder' -> Felony
  'firearm, carry without license' -> Either
  'drug, possess class a' -> Misdemeanor

### Compute `has_warrant`

Check the original `Charges` column. Split each row's charges by `;` and run `extract_warrant_type()` on each individual charge. If any charge had a warrant prefix, the row is flagged `True`.

In [21]:
## old 
def row_has_warrant(raw_charges):
    """Return True if any individual charge in the raw Charges string
    carries a warrant prefix. Returns NaN for rows with no charges."""
    if pd.isna(raw_charges):
        return np.nan
    parts = [p.strip() for p in str(raw_charges).split(";") if p.strip()]
    for part in parts:
        warrant_type, _ = extract_warrant_type(part)
        if warrant_type != "none":
            return True
    return False


df["has_warrant"] = df["cleaned_charges"].apply(row_has_warrant)

warrant_counts = df["has_warrant"].value_counts(dropna=False)
print("has_warrant value counts:")
print(warrant_counts)

# Spot-check
print("\nSample warrant rows:")
sample_warrant = df[df["has_warrant"] == True][["Charges", "cleaned_charges", "has_warrant"]].head(5)
for _, row in sample_warrant.iterrows():
    print(f"  Charges: {str(row['Charges'])[:100]}")
    print(f"  Standardized: {row['cleaned_charges']}")
    print()

has_warrant value counts:
has_warrant
NaN      423896
False      2846
True       1785
Name: count, dtype: int64

Sample warrant rows:
  Charges: UNLICENSED OPERATION OF MV c90 S10; ATTACHING WRONG MV PLATES; RECEIVE STOLEN PROPERTY -$1200 c266 S
  Standardized: unlicensed operation of mv; attaching wrong mv plates; receive stolen property -$1200; warrant charges: standard warrant: registration sticker not; standard warrant: uninsured mv/trailer; standard warrant: equipment violation, miscellaneous mv; standard warrant: unregistered motor vehicle; standard warrant: unlicensed operation of mv

  Charges: STANDARD WARRANT: ASSAULT W/DANGEROUS; WEAPON c265 S15B; STANDARD WARRANT: THREAT TO COMMIT CRIME c2
  Standardized: standard warrant: assault w/dangerous; weapon; standard warrant: threat to commit crime; standard warrant: trespass

  Charges: STANDARD WARRANT: A&B WITH DANGEROUS WEAPON; c265 S15A; STANDARD WARRANT: LARCENY FROM PERSON c266 S
  Standardized: standard warrant: a&b with dangerous weapon; standard warrant: larceny from person; standard warrant: threat to commit crime

  Charges: STANDARD WARRANT: LARCENY FROM BUILDING C266; S20 STEALING; STANDARD WARRANT: LARCENY FROM BUILDING
  Standardized: standard warrant: larceny from building stealing; standard warrant: larceny from building stealing

  Charges: DEFAULT WARRANT: LICENSE SUSPENDED, OP MV WITH; c90 S23; DEFAULT WARRANT: SHOPLIFTING BY ASPORTATION
  Standardized: default warrant: license suspended, op mv with; default warrant: shoplifting by asportation; default warrant: license suspended, op mv with, subsq.off

### Compute `is_misdemeanor`

Split `standardized_charges` by `"; "` and look up each charge's class in the lookup dict. A row is `True` only when **every** charge in the row classifies as `Misdemeanor`. Any `Felony`, `Either`, or `Unknown` charge makes the row `False`. Rows with no charges return `NaN`.

In [22]:
#gffi 
def row_is_misdemeanor(std_charges):
    """Return True if every standardized charge in the row is Misdemeanor.
    Returns False if any charge is Felony, Either, or Unknown.
    Returns NaN for rows with no charges."""
    if pd.isna(std_charges):
        return np.nan
    parts = [p.strip() for p in str(std_charges).split(";") if p.strip()]
    if not parts:
        return np.nan
    for charge in parts:
        cls = charge_class_lookup.get(charge, "Unknown")
        if cls != "Misdemeanor":
            return False
    return True


df["is_misdemeanor"] = df["cleaned_charges"].apply(row_is_misdemeanor)

misdemeanor_counts = df["is_misdemeanor"].value_counts(dropna=False)
print("is_misdemeanor value counts:")
print(misdemeanor_counts)

# Spot-check True rows
print("\nSample misdemeanor-only rows:")
sample_misd = df[df["is_misdemeanor"] == True][["Charges", "cleaned_charges", "is_misdemeanor"]].head(5)
for _, row in sample_misd.iterrows():
    print(f"  Charges: {str(row['Charges'])[:100]}")
    print(f"  Standardized: {row['cleaned_charges']}")
    print()

# Spot-check False rows (not pure misdemeanor)
print("Sample non-misdemeanor rows:")
sample_non = df[df["is_misdemeanor"] == False][["Charges", "cleaned_charges", "is_misdemeanor"]].head(5)
for _, row in sample_non.iterrows():
    print(f"  Charges: {str(row['Charges'])[:100]}")
    print(f"  Standardized: {row['cleaned_charges']}")
    print()

is_misdemeanor value counts:
is_misdemeanor
NaN      423896
False      3159
True       1472
Name: count, dtype: int64

Sample misdemeanor-only rows:
  Charges: A&B DOMESTIC NO 209A IN EFFECT
  Standardized: a&b domestic no 209a in effect

  Charges: USE MV WITHOUT AUTHORITY c90 S24; LARCENY UNDER $250 c266 S30
  Standardized: use mv without authority; larceny under $250

  Charges: DRUG, POSSESS CLASS B c94C S34
  Standardized: drug, possess class b

  Charges: LICENSE SUSPENDED, OP MV WITH c90 S23
  Standardized: license suspended, op mv with

  Charges: DRUG, POSSESS CLASS B c94C S34
  Standardized: drug, possess class b

Sample non-misdemeanor rows:
  Charges: A&B ON FAMILY / HOUSEHOLD MEMBER / INTIMATE PARTNE; STRANGULATION OR SUFFOCATION
  Standardized: a&b on family / household member / intimate partne; strangulation or suffocation

  Charges: A&B ON FAMILY / HOUSEHOLD MEMBER / INTIMATE PARTNE
  Standardized: a&b on family / household member / intimate partne

  Charges: WITNESS, INTIMIDATE c268 S13B; FALSE NAME/SS# TO LAW ENFORCEMENT; THREAT TO COMMIT CRIME c275 S2; AS
  Standardized: witness, intimidate; false name/ss# to law enforcement; threat to commit crime; assault w/dangerous weapon; kidnapping; a&b on family / household member / intimate partne; identity fraud

  Charges: TRAFFICKING CLASS B: 28+ GRAMS C94 S32E; DRUG, DISTRIBUTE CLASS B c94C S32A; DRUG, POSSESS TO DISTRI
  Standardized: trafficking class b: 28+ grams; drug, distribute class b; drug, possess to distrib class b

  Charges: WITNESS, INTIMIDATE c268 S13B; THREAT TO COMMIT CRIME c275 S2
  Standardized: witness, intimidate; threat to commit crime

### Diagnose any charges not found in lookup

Identifies standardized charges that appear in the data but are missing from `unique_charges_standardized.csv`.

In [23]:
all_std = (
    df["cleaned_charges"]
    .dropna()
    .str.split("; ")
    .explode()
    .str.strip()
    .unique()
)

missing = [c for c in all_std if c and c not in charge_class_lookup]
if missing:
    print(f"{len(missing)} standardized charges not found in lookup:")
    for c in sorted(missing):
        print(f"  {c!r}")
else:
    print("All cleaned charges found in lookup.")

995 standardized charges not found in lookup:
  '$37c(c)'
  '& $30(1)'
  '(1)'
  '500 ft of bldg'
  'a&b in the presence of a po'
  'a&b on family / household member / intimate partne'
  'a&b on police officer c265 s$13d'
  'a&b with dangerous weapon 265 si5a'
  'a&b with dangerous weapon c265 si5a'
  'address: 126 franklin st'
  'address: 155 salem st'
  'address: 20 portland st'
  'address: 205 broadway'
  'address: 25 foster st'
  'address: 3 s bowdoin st'
  'address: 30 manchester st'
  'address: 300 howard st'
  'address: 32 manchester st'
  'address: 590 broadway'
  'address: 62 bowdoin st'
  'address: 63 newbury st'
  'address: 75 haverhill st'
  'alcohol from open container in mv, drink ]'
  'assault w/dangerous weapon 265 si5b'
  'assault w/dangerous weapon c265 si5b'
  'bench warrant: a&b on family / household member / intimate'
  'bench warrant: attempt to commit crime'
  'bench warrant: b&e daytime for felony, person in fear'
  'bench warrant: contempt, criminal (common law)'
  'bench warrant: credit card fraud under $1200'
  'bench warrant: firearm, carry without license'
  'bench warrant: fugitive from justice on court'
  'bench warrant: fugitive from justice on court warrant'
  'bench warrant: larceny from person'
  'bench warrant: larceny under $1200'
  'bench warrant: motor veh, malicious damage to'
  'bench warrant: robbery, unarmed'
  'bench warrant: witness fail to appear in'
  'carrying a loaded firearm weapon'
  'child in need: a&b on family / household member / intimate'
  'child in need: a&b on police officer'
  'child in need: destruction of prop -$1200, malicious c'
  'child in need: drug, possess class b'
  'child in need: leave scene of personal injury'
  'child in need: leave scene of property damage'
  'child in need: license suspended, op mv with'
  'child in need: negligent operation of motor vehicle'
  'child in need: oui liquor'
  'child in need: reckless operation of motor vehicle'
  'child in need: resisting arrest'
  'child in need: shoplifting by concealing mdse'
  'child in need: stop for police, fail'
  'child in need: threat to commit crime'
  'child in need: unregistered motor vehicle'
  'children'
  'cocaine, possess to distribute c94c s$32a'
  'court warrant'
  'credit card fraud > $1200 by merchant'
  'criminal case'
  'criminal harrassment (m) subs off (f)'
  'damage'
  'dangerous weapon, carry, 2nd off.'
  'deface property (tagging)'
  'defacement malicious wanton property c266 s$126a'
  'default warrant: 2012 traff over 18grams'
  'default warrant: a&b'
  'default warrant: a&b : serious bodily injury'
  'default warrant: a&b on +60/disabled'
  'default warrant: a&b on ambulance personnel'
  'default warrant: a&b on correction officer'
  'default warrant: a&b on family / household'
  'default warrant: a&b on family / household member /'
  'default warrant: a&b on police officer'
  'default warrant: a&b on public employee'
  'default warrant: a&b with dangerous weapon'
  'default warrant: a&b with dangerous weapon 265 si5a'
  'default warrant: abuse prevention order, violate'
  'default warrant: affray (common law)'
  'default warrant: alcohol from open container in mv, drink'
  'default warrant: animal, cruelty to'
  'default warrant: any person trafficks fentanyl more than'
  'default warrant: any person trafficks fentanyl more than 10 grams'
  'default warrant: assault'
  'default warrant: assault by means hypodermic syringe'
  'default warrant: assault in dwelling, armed'
  'default warrant: assault on ambulance personnel'
  'default warrant: assault to murder'
  'default warrant: assault w/dangerous weapon'
  'default warrant: attempt to commit crime'
  'default warrant: b&e daytime for felony'
  'default warrant: b&e for misdemeanor'
  'default warrant: b&e nighttime for felony'
  'default warrant: b&e nighttime for felony c266'
  'default warrant: body armor, use in felony'
  'default warrant: brakes violation, mv'
  'default warrant: breakdown lane violation'
  'default warrant: building, vandalize'
  'default warrant: burglarious instrument,'
  'default warrant: burglarious instrument, possess'
  'default warrant: burn personalty'
  'default warrant: carjacking'
  'default warrant: carrying a loaded firearm'
  'default warrant: carrying a loaded firearm weapon'
  'default warrant: check, forgery of'
  'default warrant: check, utter false'
  'default warrant: cocaine, distribute, subsq.off.'
  'default warrant: cocaine, trafficking in - over'
  'default warrant: cocaine, trafficking in - over 14 grams'
  'default warrant: conspiracy'
  'default warrant: conspiracy to violate drug'
  'default warrant: conspiracy to violate drug law'
  'default warrant: contribute to delinquency of child'
  'default warrant: correctional institution, disturb'
  'default warrant: counterfeit note, possess'
  'default warrant: credit card fraud < $1200 by merchant )'
  'default warrant: credit card fraud under $1200'
  'default warrant: credit card, improper use'
  'default warrant: credit card, improper use under $1200'
  'default warrant: credit card, larceny of'
  'default warrant: credit card, receive stolen'
  'default warrant: criminal harrassment (m) subs off (f)'
  'default warrant: dangerous weapon on school'
  'default warrant: dangerous weapon, carry'
  'default warrant: dangerous weapon, carry, 4th off.'
  'default warrant: deface property'
  'default warrant: defacement malicious'
  'default warrant: defacement malicious wanton'
  'default warrant: defacement malicious wanton property'
  'default warrant: defective equipment'
  'default warrant: destruction of prop +$1200,'
  'default warrant: destruction of prop +$1200, malicious c 266'
  'default warrant: destruction of prop +$1200, wanton c'
  'default warrant: destruction of prop -$1200,'
  'default warrant: destruction of prop -$1200, malicious c 266'
  'default warrant: disguise to obstruct justice'
  'default warrant: disorderly conduct'
  'default warrant: disorderly conduct c'
  'default warrant: disturbing the peace'
  'default warrant: dna database sample,refuse'
  'default warrant: dna database sample,refuse provide'
  'default warrant: drug violation near'
  'default warrant: drug violation near school/park'
  'default warrant: drug, distribute class a'
  'default warrant: drug, distribute class a c94c'
  'default warrant: drug, distribute class b'
  'default warrant: drug, distribute class b, subsq. off.'
  'default warrant: drug, distribute class d (effective'
  'default warrant: drug, distribute class e'
  'default warrant: drug, possess class a'
  'default warrant: drug, possess class a,'
  'default warrant: drug, possess class a, subsq.off.'
  'default warrant: drug, possess class b'
  'default warrant: drug, possess class b,'
  'default warrant: drug, possess class b, subsq.off.'
  'default warrant: drug, possess class c'
  'default warrant: drug, possess class d'
  'default warrant: drug, possess class e'
  'default warrant: drug, possess to distrib class'
  'default warrant: drug, possess to distrib class a'
  'default warrant: drug, possess to distrib class b'
  'default warrant: drug, possess to distrib class b c94c s$32a'
  'default warrant: drug, possess to distrib class d'
  'default warrant: drug, possess to distrib class e'
  'default warrant: electronic device, use while operating, mv,'
  'default warrant: equipment violation, miscellaneous mv'
  'default warrant: false id info, arrst furni to'
  'default warrant: false id info, arrst furni to law enf'
  'default warrant: false pretense of trade, obtain goods by'
  'default warrant: feeding device, possess large capacity'
  'default warrant: fire call box, tamper with'
  'default warrant: firearm in vehicle, leave'
  'default warrant: firearm serial no., deface'
  'default warrant: firearm use in felony'
  'default warrant: firearm w/defaced no., receive'
  'default warrant: firearm within 500 ft of dwelling'
  'default warrant: firearm without fid card,'
  'default warrant: firearm without fid card, possess'
  'default warrant: firearm, carry without'
  'default warrant: firearm, carry without license'
  'default warrant: firearm, carry without license, 3rd off.'
  'default warrant: firearm, carry without license, 4th off.'
  'default warrant: firearm, discharge within 500 ft of bldg'
  'default warrant: firearms, trafficking in 3-9'
  'default warrant: fireworks, possess unlawful'
  'default warrant: forgery of document'
  'default warrant: fugitive from justice on'
  'default warrant: fugitive from justice on court warrant'
  "default warrant: fugitive from justice on gov's warrant"
  'default warrant: fugitive, fail bring before court'
  'default warrant: harassment prevention'
  'default warrant: heroin, being present where kept'
  'default warrant: heroin/morphine/opium,'
  'default warrant: heroin/morphine/opium, trafficking in'
  'default warrant: home invasion'
  'default warrant: hypodermic, possess'
  'default warrant: identify self, mv operator'
  'default warrant: identify self, mv operator refuse'
  'default warrant: identity fraud'
  'default warrant: in control of a large capacity weapon or large cap'
  'default warrant: inspection/sticker, no'
  'default warrant: juror fail to attend'
  'default warrant: keep right for oncoming mv, fail to'
  'default warrant: kidnapping'
  'default warrant: larceny by check over $1200'
  'default warrant: larceny by check over $1200 & s30(1)'
  'default warrant: larceny by check under $1200 &'
  'default warrant: larceny by check under $1200 & s30'
  'default warrant: larceny from building'
  'default warrant: larceny from building stealing'
  'default warrant: larceny from person'
  'default warrant: larceny over $1200'
  'default warrant: larceny over $1200 by single'
  'default warrant: larceny over $1200 by single scheme'
  'default warrant: larceny over $250 by false'
  'default warrant: larceny under $1200'
  'default warrant: larceny under $1200 by single scheme'
  'default warrant: larceny under $1200 by single scheme 266'
  'default warrant: larceny under $250 by false pretense'
  'default warrant: leave scene of personal injury'
  'default warrant: leave scene of property'
  'default warrant: leave scene of property damage'
  'default warrant: lewdness, open and gross'
  'default warrant: license not in possession'
  'default warrant: license revoked as hto, operate mv with'
  'default warrant: license suspended for oui, oper mv with'
  'default warrant: license suspended, op mv with'
  'default warrant: license suspended, op mv with,'
  'default warrant: license suspended, op mv with, subsq.off'
  "default warrant: license, exhibit another's"
  'default warrant: license, false application for'
  'default warrant: license, false application for mv'
  'default warrant: lights violation'
  'default warrant: lights violation, mv'
  'default warrant: liquor to person under 21, sell/deliver'
  'default warrant: liquor, person under 21'
  'default warrant: liquor, person under 21 possess'
  'default warrant: marihuana, possess'
  'default warrant: marked lanes violation'
  'default warrant: mayhem'
  'default warrant: miscellaneous munic ordinance/bylaw'
  'default warrant: miscellaneous statutory'
  'default warrant: motor carrier safety violation 540 cmr'
  'default warrant: motor veh by-law violation'
  'default warrant: motor veh in felony/larceny,'
  'default warrant: motor veh, larceny of'
  'default warrant: motor veh, malicious damage'
  'default warrant: motor veh, malicious damage to'
  'default warrant: motor veh, receive stolen'
  'default warrant: motor veh, receive stolen, subsq.off.'
  'default warrant: municipal by-law or'
  'default warrant: negligent operation of motor'
  'default warrant: negligent operation of motor vehicle'
  'default warrant: nightwalker, common'
  'default warrant: noisy and disorderly house,'
  'default warrant: note, forgery of bank'
  'default warrant: notes, possess worthless/false'
  'default warrant: number plate violation'
  'default warrant: number plate violation to'
  'default warrant: number plate violation to conceal id'
  'default warrant: operation of motor vehicle,'
  'default warrant: operation of motor vehicle, improper'
  'default warrant: oui drugs'
  'default warrant: oui liquor'
  'default warrant: oui liquor or .08%, 9th offense'
  'default warrant: oui liquor, 2nd offense'
  'default warrant: persons previously convicted of 1 violent'
  'default warrant: persons previously convicted of 2 violent crimes o'
  'default warrant: police officer, interfere with (common law)'
  'default warrant: possession of ammunition'
  'default warrant: prisoner, deliver drugs to'
  'default warrant: railroad track, walk/ride on'
  'default warrant: rape of child, statutory'
  'default warrant: receive stolen prop -$1200, subsq. off'
  'default warrant: receive stolen property'
  'default warrant: receive stolen property +$1200'
  'default warrant: receive stolen property -$1200'
  'default warrant: reckless endangerment to children'
  'default warrant: reckless operation of motor'
  'default warrant: reckless operation of motor vehicle'
  'default warrant: recognizance, fail appear upon'
  'default warrant: registration sticker missing 540 cmr s 2.05'
  'default warrant: registration suspended, op mv'
  'default warrant: registration suspended, op mv with'
  'default warrant: resisting arrest'
  'default warrant: resisting arrest c'
  'default warrant: right lane, fail drive in'
  'default warrant: rmv document, forge/misuse'
  'default warrant: rmv document, possess/use false/stolen'
  'default warrant: rmv id card address change'
  'default warrant: rmv signature, forge/misuse'
  'default warrant: robbery, armed'
  'default warrant: robbery, armed & masked'
  'default warrant: robbery, unarmed'
  'default warrant: safety standards, mv not meeting rmv'
  'default warrant: seat belt, fail wear'
  'default warrant: sex offender fail to register'
  'default warrant: sexual conduct for fee'
  'default warrant: sexual conduct for fee c272'
  'default warrant: shoplifting $250+ by'
  'default warrant: shoplifting $250+ by asportation'
  'default warrant: shoplifting by asportation'
  'default warrant: shoplifting by asportation,'
  'default warrant: shoplifting by asportation, 2nd'
  'default warrant: shoplifting by asportation, 2nd off.'
  'default warrant: shoplifting by asportation, 3rd off.'
  'default warrant: shoplifting by concealing'
  'default warrant: shoplifting by concealing mdse'
  'default warrant: shoplifting by concealing mdse, 2nd off.'
  'default warrant: shoplifting by concealing mdse, 3rd off.'
  'default warrant: signal, fail to'
  'default warrant: speeding'
  'default warrant: speeding in violation special regulation'
  'default warrant: state hway traffic violation 720 cmr s9.06'
  'default warrant: state hway traffic violation 720 cmr s9.07'
  'default warrant: stop for police, fail'
  'default warrant: stop/yield, fail to'
  'default warrant: telephone calls, annoying'
  'default warrant: threat to commit crime'
  'default warrant: trafficking class a: 200+'
  'default warrant: trafficking class a: 28+ grams'
  'default warrant: trafficking class b: 100+'
  'default warrant: trafficking class b: 100+ grams'
  'default warrant: trafficking class b: 200+ grams'
  'default warrant: trafficking class b: 28+ grams'
  'default warrant: trespass'
  'default warrant: trespass c'
  'default warrant: truck, b&e for felony'
  'default warrant: turn, improper'
  'default warrant: uninsured mv/trailer'
  'default warrant: unl possession ammo no fid'
  'default warrant: unlawful carring of firearms'
  'default warrant: unlicensed operation of mv'
  'default warrant: unlicensed operation of mv 90'
  'default warrant: unregistered motor vehicle'
  'default warrant: use mv without authority'
  'default warrant: use mv without authority, 3rd off.'
  'default warrant: use of mobile telephone or device uner 18'
  'default warrant: utter false instrument'
  'default warrant: window obstructed/nontransparent'
  'default warrant: wit/juror/pol/court official,'
  'default warrant: wit/juror/pol/court official, intimidate'
  'default warrant: wit/juror/pol/crt official,'
  'destruction of prop +$1200, malicious c'
  'destruction of prop +$1200, wanton c'
  'destruction of prop -$1200, malicious c'
  'destruction of prop -$1200, wanton c'
  'disorderly conduct c'
  'disorderly conduct, subsq. off.'
  'distribute, subsq.off.'
  'dog/cat, motorist fail report injury to'
  'drug paraphernalia, pos/pur to dist ](a)'
  'drug, distribute class a, subsq.off.'
  'drug, distribute class b, subsq. off.'
  'drug, distribute class d (effective 1/5/8'
  'drug, pos to distrib class b, subsq.'
  'drug, poss to dist class d, subsq.'
  'drug, possess class a, subsq.off.'
  'drug, possess class b, subsq.off.'
  'drug, possess to distrib class a, subsq.'
  'drug, possess to distrib class b c94c s$32a'
  'electronic device, use while operating, mv, 1st of'
  'electronic device, use while operating, mv, ist of'
  'enter at night for felony,person in fear'
  'failure to obey traffic sign or signal`'
  'ffrearm, carry without license'
  'firearm without fid card, subsq.off.'
  'firearm, carry without license, 2nd off.'
  'firearm, carry without license, 3rd off.'
  'firearm, carry without license, 4th off.'
  'grams'
  'headlights, fail dim 540 cmr s 22.05'
  'in control of a large capacity weapon or large cap'
  'injury'
  'items or services bearing or identified by counter'
  'larceny by check over $1200 & s30(1)'
  'larceny by check under $1200 & s30(1)'
  'larceny from building stealing'
  'law'
  'law enf'
  'lawrence police department'
  'leave scene of personal injury & death'
  'license'
  'license suspended, op mv with, subsq.off'
  'license, 2nd off.'
  'license, 3rd off.'
  'license, 4th off.'
  'lights violation'
  'marine fish striped bass viol (civil) 322 cmr s6.0'
  'mdse'
  'miscellaneous munic ordinance/bylaw'
  'miscellaneous munic ordinance/bylaw viol'
  'motor veh, larceny of, subsq.off.'
  'motor veh, malicious damage to,subsq.off'
  'motor veh, receive stolen, subsq.off.'
  'motor vehicle'
  'municipal by-law or ordinance viol (civ)'
  'mv with'
  'notes, possess worthless/false'
  'operating mv, 2nd off'
  'operation of motor vehicle, improper'
  'ordinance violation'
  'ordinance/bylaw viol'
  'oui drugs, 3rd offense'
  'oui drugs, 4th offense'
  'oui liquor, 2nd offense'
  'oui liquor, 3rd offense'
  'penalty of perjury c268 sia'
  'persons previously convicted of 1 violent crimes o'
  'persons previously convicted of 2 violent crimes o'
  'persons previously convicted of 3 violent crimes o'
  'possess'
  'property'
  'receive stolen property +$1200, subsq'
  'register, subsq. off'
  'resisting arrest c'
  'resisting arrest c268 s$32b'
  's$30(1)'
  'shoplifting by asportation, 2nd off.'
  'shoplifting by asportation, 3rd off.'
  'shoplifting by concealing mdse, 3rd off.'
  'snow/rec vehicle violation 323 cmr s3.03'
  'standard warrant:'
  'standard warrant: a&b'
  'standard warrant: a&b : pregnant victim'
  'standard warrant: a&b on +60/disabled'
  'standard warrant: a&b on ambulance'
  'standard warrant: a&b on ambulance personnel'
  'standard warrant: a&b on correction officer'
  'standard warrant: a&b on family / household'
  'standard warrant: a&b on family / household member /'
  'standard warrant: a&b on police officer'
  'standard warrant: a&b to intimidate for'
  'standard warrant: a&b with dangerous weapon'
  'standard warrant: a&b with dangerous weapon +60 c265 sisa'
  'standard warrant: a&b with dangerous weapon 265 si15a'
  'standard warrant: a&b with dangerous weapon 265 si5a'
  'standard warrant: a&b with dangerous weapon c265 si5a'
  'standard warrant: abandon mv'
  'standard warrant: abuse prevention order,'
  'standard warrant: abuse prevention order, violate'
  'standard warrant: accessory after the fact'

### Verify & summarize

In [24]:
charged_rows = df[df["cleaned_charges"].notna()]

print(f"Total rows: {len(df):,}")
print(f"Rows with charges: {len(charged_rows):,}")
print()
print(f"has_warrant = True  : {(df['has_warrant'] == True).sum():,}")
print(f"has_warrant = False : {(df['has_warrant'] == False).sum():,}")
print(f"has_warrant = NaN   : {df['has_warrant'].isna().sum():,}")
print()
print(f"is_misdemeanor = True  : {(df['is_misdemeanor'] == True).sum():,}")
print(f"is_misdemeanor = False : {(df['is_misdemeanor'] == False).sum():,}")
print(f"is_misdemeanor = NaN   : {df['is_misdemeanor'].isna().sum():,}")
print()
print(f"Final shape: {df.shape}")
print(f"Columns: {list(df.columns)}")

Total rows: 428,527
Rows with charges: 4,631

has_warrant = True  : 1,785
has_warrant = False : 2,846
has_warrant = NaN   : 423,896

is_misdemeanor = True  : 1,472
is_misdemeanor = False : 3,159
is_misdemeanor = NaN   : 423,896

Final shape: (428527, 23)
Columns: ['Date', 'Type', 'Location', 'Arrested', 'Location Prefix', 'DOB', 'Charges', 'raw_address', 'latitude', 'longitude', 'geocode_confidence', 'person_id', 'category', 'Year', 'crime_severity', '_DOB_raw', '_Date_raw', 'DOB_dt', 'Date_dt', 'statutes', 'cleaned_charges', 'has_warrant', 'is_misdemeanor']

### Save checkpoint15

In [26]:
df.to_csv(OUT_PATH, index=False)
print(f"Saved checkpoint15: {OUT_PATH}")
print(f"Shape: {df.shape}")

Saved checkpoint15: /Users/sreej/Desktop/Gateway_lawrence/gatewayinitiative-lawrencepd/scripts/charges/../data/missing_dates_csv/md_checkpoints/checkpoint15_misdemeanor_warrant.csv
Shape: (428527, 23)